#!/bin/sh

set -e

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

if [ -x /bin/btrfs ]
then
	copy_exec /bin/btrfs /bin
	copy_exec /bin/btrfs-zero-log
	if [ ! -x /usr/share/initramfs-tools/hooks/fsck ] && [ ! -x /etc/initramfs-tools/hooks/fsck ]
	then
	    copy_exec /bin/fsck.btrfs /bin
	fi
fi
